app/models/app.py
from app.core.db import db


class Immobile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bedrooms = db.Column(db.Integer, unique=False, nullable=True)
    bathrooms = db.Column(db.Integer, unique=False, nullable=True)
    parking = db.Column(db.Integer, unique=False, nullable=True)
    area = db.Column(db.Integer, unique=False, nullable=True)
    neighborhood = db.Column(db.Integer, unique=False, nullable=True)
    s_neighborhood = db.Column(db.String, unique=False, nullable=True)
    validate = db.Column(db.Boolean, unique=False, nullable=True)
    price = db.Column(db.Float, unique=False, nullable=True)
    correct_value = db.Column(db.Float, unique=False, nullable=True)

app/forms/tenement.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange
# from wtforms.fields.html5 import IntegerField, DecimalField
from wtforms.widgets.html5 import NumberInput
class Tenement(FlaskForm):
    bedrooms = IntegerField('Quartos', validators=[NumberRange(0, 100, message='Aceitos apenas números entre 0 e 100')], widget=NumberInput(min=0, max=100, step=1))
    bathrooms = IntegerField('Banheiros', validators=[NumberRange(0, 100, message='Aceitos apenas números entre 0 e 100')], widget=NumberInput(min=0, max=100, step=1))
    parking = IntegerField('Vagas', validators=[NumberRange(0, 100, message='Aceitos apenas números entre 0 e 100')] , widget=NumberInput(min=0, max=100, step=1))
    area = IntegerField("Area", validators=[NumberRange(0, 100, message='Aceitos apenas números entre 0 e 100')] , widget=NumberInput(min=0, max=100, step=1))
    neighborhood = StringField('Bairro', validators=[DataRequired('Item obrigatório')])
    submit = SubmitField('Enviar')

app/__init__.py
from flask import Flask
from app.core.configure import configure
from app.config.config import config


def create_app(mode='production'):
    app = Flask(__name__)
    app.config.from_object(config[mode])
    configure(app)
    return app

app/blueprints/__init__.py
import importlib
import pkgutil
from flask import Blueprint

def register_blueprints(app):
    '''
    Factory to iter each file in ´blueprints folder´ and register in ´app´ 
    '''
    for module_info, name, ispkg in pkgutil.iter_modules(__path__):
        module = importlib.import_module(f'{__name__}.{name}')
        if hasattr(module, 'bp'):
            bp = getattr(module,'bp')
            if isinstance(bp, Blueprint):
                app.register_blueprint(bp)

app/blueprints/api.py
import json
from flask import Blueprint, current_app as app, render_template, request, jsonify, abort, url_for

from app.forms.tenement import Tenement
from app.kernel.sci import Pipeline
from app.models.app import Immobile
from app.core.db import db

bp = Blueprint('api', __name__, url_prefix='/api')

@bp.route('/get_price', methods=['POST'])
def get_price():
    '''TODO: Criar função para receber um json com os dados do apartamento, 
    calcular o valor do preço do aluguel e retornar em reais.
    '''
    form = Tenement()
    im = Immobile()
    if form.validate_on_submit():
        pipeline = Pipeline()
        pipeline.load(
            form.bedrooms.data, 
            form.bathrooms.data, 
            form.parking.data,
            form.area.data,
            form.neighborhood.data
            )
        predict = pipeline.predict()
        im.bedrooms = form.bedrooms.data
        im.bathrooms = form.bathrooms.data
        im.parking = form.parking.data
        im.area = form.area.data
        im.s_neighborhood = form.neighborhood.data 
        im.neighborhood = pipeline.get_neighborhood_id(im.s_neighborhood)
        im.price = predict['original']
        db.session.add(im)
        db.session.commit()
        return jsonify({'valor': predict['monetary'],
                        'id': im.id,
                        'url_validate': url_for('api.validate', id=im.id, type=True),
                        'url_correct': url_for('api.correct', id=im.id)})
    return abort(404)
@bp.route('/validate/<int:id>/<type>')
def validate(id:int, type: str):
    '''Valida um determinado ID'''
    im = Immobile.query.filter(Immobile.id == id).first_or_404()
    if not im.validate is None:
        return jsonify({'status': False, 'message':'Validação já feita, não é possível alterar'})
    if type == 'VALID':
        im.validate = True
    else:
        im.validate = False
    db.session.commit()
    return jsonify({'status':True})

@bp.route('correct/<int:id>', methods=['POST'])
def correct(id: int):
    'Corrige o valor do aluguel de acordo com informação inserida pelo usuário.'
    print(request.form.get('input-correct-value'))
    im = Immobile.query.filter(Immobile.id == id).first_or_404()
    if request.form.get('input-correct-value', False) != False:
        im.correct_value = request.form.get('input-correct-value')
        db.session.commit()
        return jsonify({'status': True})
    return jsonify({'status': False})

app/blueprints/main.py
from flask import Blueprint, current_app as app, render_template, url_for, redirect
from app.forms.tenement import Tenement
from app.kernel.sci import Pipeline

bp = Blueprint("main", __name__, url_prefix="/")

@bp.route('/', methods=['GET', 'POST'])
def index():
    form = Tenement()
    # if form.validate_on_submit():
    #     pipeline = Pipeline()
    #     pipeline.load(
    #         form.bedrooms.data, 
    #         form.bathrooms.data, 
    #         form.parking.data,
    #         form.area.data,
    #         form.neighborhood.data
    #         )
    #     predict = pipeline.predict()
    #     print(pipeline.data)
    #     print(pipeline.predict_value_real)
    #     return render_template('index.html', form=form, predict=predict)

    return render_template('index.html', form=form)

app/templates/base.html
<!doctype html>
<html lang="pr-br">

<head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    {% block styles %}
    <!-- Bootstrap CSS -->
    <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/fontawesome/all.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/bootstrap-select/bootstrap-select.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/jquery/jquery-ui.min.css')}}" rel="stylesheet"> {% endblock %}

    <title>
        {% block title %} {% if title %}{{ title }} - {{config['SITE_TITLE']}}{% else %}{{config['SITE_TITLE']}} - Calculadora de Aluguel{% endif %} {% endblock %}
    </title>
    {% endblock %}
</head>

<body>



    {% block content %}
    <main class="container pb-5">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category if category else 'info' }}" role="alert">{{ message }}</div>
        {% endfor %} {% endif %} {% endwith %} 
         {% block app_content %} {% endblock %}
    </main>
    {% endblock %} 

    <!-- <footer class="footer fixed-bottom mt-auto py-2 bg-dark">
        <div class="container d-flex justify-content-around">
            <span class="text-muted">Calculadora de Aluguel</span>
        </div>

    </footer> -->

    {% block scripts %}
    <script src="{{url_for('static', filename='js/jquery/jquery.min.js')}}" type="text/javascript"></script>

    <script src="{{url_for('static', filename='js/bootstrap/bootstrap.bundle.min.js')}}" type="text/javascript"></script>

    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}
{% import "macros/form.html" as macros %}

{% block app_content %}

<div id='main_content' class="containter">
    <h3>Calculadora de Aluguel</h3>
    <form method="POST" id='main_form' action="{#{{url_for('api.get_price')}}#}">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-sm">
                {{macros.render_field(form.bedrooms,class='form-control')}}
            </div>
            <div class="col-sm">
                {{macros.render_field(form.bathrooms, class='form-control')}}
            </div>
            <div class="col-sm">
                {{macros.render_field(form.parking, class='form-control')}}
            </div>
            <div class="col-sm">
                {{macros.render_field(form.area, class='form-control')}}
            </div>

            {{macros.render_field(form.neighborhood, class='form-control')}}

        </div>
        <br>
        <div class="row">
            {{ macros.render_field(form.submit, class="btn btn-primary", nolabel=True)}}

        </div>
    </form>
</div>
<br>
<br>
<!-- {% if predict %}

<div class="p-3 mb-2 bg-success text-white">Valor estimado do apartamento: {{predict}}</div>
{% endif %} -->
<div id='result' class="p-3 mb-2 bg-success text-white rounded h5" style="display: none;"></div>
{% endblock %}

{% block scripts %} {{ super() }}
<script type="text/javascript">
    $('#main_form').submit(function (event) {
        var form = $(this);
        event.preventDefault()
        $.ajax({
            url: "{{url_for('api.get_price')}}",
            type: "POST",
            data: form.serialize(),
            success: function (data) {
                $('#result').show()
                $('#result').empty()
                $('#result').append('<p id="valor">Valor estimado do aluguel do imóvel é de: ' 
                    + data['valor'] + "</p><hr>" )
                $("#result").append('<div id="values-container"></div>')
                $("#values-container").append('<p id="confirm-value">Os dados estão ok? <a href=' 
                    + data["url_validate"]+' class="link-dark confirm_rent_value">Sim</a></p>'
                    + '<p id="incorrect-value">Os valoes estão errados, informe o valor que você gostaria de aluguar:'
                    + '<p id="p_new_value"></p>')
                $('#p_new_value').append('<form id="new-value" action='+ data["url_correct"] +'></form>')
                $('#new-value').append('<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>')
                $('#new-value').append('<input class="form-control" id="input-correct-value" max="100000" min="100" name="input-correct-value" placeholder="" size="" step="1" type="number" value="">')
                $('#new-value').append('<input class="btn btn-primary" id="submit" name="submit" placeholder="" size="" type="submit" value="Enviar">')
                
            }
        });
    })

    $(document).on('submit', '#new-value', function (event) {
        var form = $(this);
        event.preventDefault()
        $.ajax({
            url: form.attr('action'),
            type: "POST",
            data: form.serialize(),
            success: function (data) {
                if (data['status'] == true){
                    $("#values-container").empty()
                    $("#values-container").append('Obrigado, salvamos os dados')
                } else {
                    $("#values-container").append('Ocorreu um erro, tente novamente')
                }
                 }
        });
    })
    $(document).on("click", '.confirm_rent_value', function(event) { 
        event.preventDefault();
        var link = $(this)
        $.ajax({
            url: link.attr('href'),
            type: 'GET',
            success: function(data){
                console.log(data)
                $('#values-container').empty()
                $('#values-container').append('<p id="confirmed-value">Obrigado, salvamos sua confirmação.</p>')
            }
            
        })
    });
</script>
{% endblock %}

app/templates/macros/form.html
{% macro render_field(field, size, class, placeholder, nosize, nolabel) %}
{% if nolabel %}
{{ field.label(class='visually-hidden') }}
{% else %}
{{ field.label(class='form-label') }}
{% endif %}
{% if style %}
{{ field(class=(class if class else '') + (" is-invalid" if field.errors else ""), size=size, placeholder=placeholder,
style=style, **kwargs)|safe }}
{% else %}
{% if nosize %}
{{ field(class=(class if class else '') + (" is-invalid" if field.errors else ""), **kwargs)|safe }}
{% else %}
{{ field(class=(class if class else '') + (" is-invalid" if field.errors else ""), size=size, placeholder=placeholder,
**kwargs)|safe }}
{% endif %}
{% endif %}
{% if field.errors %}
<!-- <ul class='invalid-feedback'> -->
{% for error in field.errors %}
<!-- <li>{{ error }}</li> -->
<div class='invalid-feedback'>{{ error }} </div>
{% endfor %}
<!-- </ul> -->
{% endif %}
{% endmacro %}